global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node.js Application - Main metrics
  - job_name: 'restaurant-app'
    metrics_path: '/metrics'
    scrape_interval: 30s
    static_configs:
      - targets: ['app:3000']
